[package]
name = "rocket-webapi"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.0"
chrono = "0.4.3"
